---
- hosts: all
  gather_facts: no
  connection: local
  tasks:
    - name: show system license and chassis firmware
      junipernetworks.junos.junos_command:
        commands:
        - show chassis firmware
        display: json
      register: firmware
      when: junso_hw_model != 'QFX5220-128C'

    - name: debug firmware
      debug: var=firmware.stdout.0
      when: false
      # when: junso_hw_model != 'QFX5220-128C'

    - name: cut noise from the firmware data
      ansible.builtin.set_fact:
        firmware_data: "{{ firmware.stdout.0 | split('\n\n') | first }}"
      when: junso_hw_model != 'QFX5220-128C'

    - name: bios version
      debug:
        msg: "{{inventory_hostname}} | {{ansible_host}} | BIOS | {{ item['firmware-version'].0['data'] }}"
      loop: "{{ firmware_data['firmware-information'].0['chassis'].0['chassis-module'].0['firmware'] }}"
      loop_control:
        label: item
      when:
      - item['type'].0['data'] == 'BIOS'
      - junso_hw_model != 'QFX5220-128C'

